version: "3"
services:
  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001
  todotests:
    image: todotests
    restart: always
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
